### ISSUE TITLE
immer-store browser extension

### ISSUE THREAD

**Issue by amirHossein-Ebrahimi** [christianalfoni/immer-store#7]
Is there any plan to implement a browser extension for immer-store, something like the redux-dev tool

**Comment by christianalfoni** [comment]
From the README: "!NOTE This project is not officially released, as it would require more testing and a maintainer." 😄 

If you are up for it I am happy to transfer the repo to you?

**Comment by amirHossein-Ebrahimi** [comment]
The offer was beautiful and tempting, I think I can handle it

**Comment by christianalfoni** [comment]
Sorry for delay, invited for transfer now 😄
